version: '3.0'

volumes:
  database_data:
    driver: local

services:

  postgres:
    image: postgres:15.1-alpine
    container_name: expert-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data