create table if not exists facts (
    id bigint generated by default as identity primary key,
    description varchar(512) not null,
    weight decimal not null
);

create table if not exists jobs (
    id bigint generated by default as identity primary key,
    name varchar(128) not null
);

create table if not exists trust (
    id bigint generated by default as identity primary key,
    fact_id bigint references facts (id),
    job_id bigint references jobs (id),
    trust_cf decimal not null,
    constraint unique_fact_job unique (fact_id, job_id)
);